name: Do Not Submit

on:
  pull_request:
    branches: ['main']

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - uses: chainguard-dev/actions/donotsubmit@5e21cb47971231c078a677dfe89a348371cb880c # main
